In [10]:
import pandas as pd

In [25]:
df = pd.read_excel('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/Attribute DataSet.xlsx')

In [26]:
type(df)
# data frame means it's a tabular structure

pandas.core.frame.DataFrame

In [27]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [32]:
pd.read_excel('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/Attribute DataSet.xlsx', sheet_name = 'Madhu')

      dnsamdv Unnamed: 1 Unnamed: 2
0      dmvasm     mfnvbm        NaN
1     mdv.,as    mdf nvm        NaN
2  .,sd v.,s       m fvm    ,mfv ,m
3   ,fmvlkfnj      m nvm        fvd
4      lfnlvn       ,m v        fdf
5       ldfnv         m     fghdfgh
6         NaN        NaN     dfhgds

In [35]:
pd.read_excel('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/Attribute DataSet.xlsx', sheet_name = 'Madhu', header = None, names = ['A', 'B', 'C'])

            A        B        C
0     dnsamdv      NaN      NaN
1      dmvasm   mfnvbm      NaN
2     mdv.,as  mdf nvm      NaN
3  .,sd v.,s     m fvm  ,mfv ,m
4   ,fmvlkfnj    m nvm      fvd
5      lfnlvn     ,m v      fdf
6       ldfnv       m   fghdfgh
7         NaN      NaN   dfhgds

In [36]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [38]:
# If I want to see only 2 record
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [40]:
# if no parameter given by default it displays starting 5 records
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [42]:
# tail function displays last 5 records
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [48]:
pd.read_csv('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/haberman.csv', header = None, names = ['Age', "Patient's year of operation", 'Number of positive', 'Survival status'])

     Age  Patient's year of operation  Number of positive  Survival status
0     30                           64                   1                1
1     30                           62                   3                1
2     30                           65                   0                1
3     31                           59                   2                1
4     31                           65                   4                1
..   ...                          ...                 ...              ...
301   75                           62                   1                1
302   76                           67                   0                1
303   77                           65                   3                1
304   78                           65                   1                2
305   83                           58                   2                2

[306 rows x 4 columns]

In [52]:
pd.read_csv('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/haberman1.csv')

      30@64@1@1
0     30@62@3@1
1     30@65@0@1
2     31@59@2@1
3     31@65@4@1
4    33@58@10@1
..          ...
300   75@62@1@1
301   76@67@0@1
302   77@65@3@1
303   78@65@1@2
304   83@58@2@2

[305 rows x 1 columns]

In [51]:
# in this case where '@' is a delimeter. using sep = '@' we can seperate the data a
pd.read_csv('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/haberman1.csv', sep= '@')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [53]:
# get the dataset directly from github repository. Click 'Raw' in github and paste the link here as below.
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv')

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [61]:
# read data directly from github repository
pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/BCF.csv')

           date  values.I2P  values.P2I  values.JPI
0    1996-04-01   -2.580556   -0.836444        63.3
1    1996-05-01   -2.882258   -1.972581        66.3
2    1996-06-01   -1.742778   -0.478778        59.7
3    1996-07-01   -0.397796   -1.574301        63.3
4    1996-08-01   -0.977151   -1.797312        63.8
..          ...         ...         ...         ...
112  2005-08-01   -2.144935   -1.646989        49.0
113  2005-09-01   -3.543270   -1.769889        49.9
114  2005-10-01   -4.500484   -2.309946        50.6
115  2005-11-01   -4.098556   -1.528611        57.4
116  2005-12-01   -5.797043   -2.872849        52.9

[117 rows x 4 columns]

In [62]:
# read a html page which contains table
a = pd.read_html('https://www.basketball-reference.com/leagues/NBA_2015_totals.html')

In [60]:
# a html page can have multiple table which means multiple data frame so html page always returns all the table in form of list
type(a)

list

In [63]:
# since this html page contains only one table hence len(a) is 1
len(a)

1

In [67]:
# since this html page has only one table hence we can get the data using indexing in list i.e a[0]
a[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [68]:
# read json data from browser by giving link directly
# 1 single row is treated as 1 sinle dictionary inside json data

pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app,state_reason
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52121,1636317632,PR_kwDOAA0YD85Mq_-O,52121,Backport PR #52076 on branch 2.0.x (BUG: Fix r...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,#52076,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52120,1636248030,PR_kwDOAA0YD85MqxJP,52120,PERF: Groupby aggregations with Categorical,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,```\r\nimport numpy as np\r\nnp.random.seed(94...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52119,1636219983,PR_kwDOAA0YD85MqrGS,52119,Backport PR #52107 on branch 2.0.x (CI: Correc...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Backport PR #52107: CI: Correctly set PANDAS_C...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52118,1636192962,I_kwDOAA0YD85hhlLC,52118,BUG: `pandas.read_csv()` does not work in comb...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52117,1636190392,I_kwDOAA0YD85hhki4,52117,BUG: Timestamp fails when fold is passed and b...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52116,1636177413,I_kwDOAA0YD85hhhYF,52116,DEPR: Deprecate returning a DataFrame in Serie...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Feature Type\r\n\r\n- [ ] Adding new funct...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52115,1635508391,PR_kwDOAA0YD85MoTBI,52115,BUG: agg in non-unique col,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #51099 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52114,1635134270,PR_kwDOAA0YD85MnCZM,52114,Add fillna_method 'pad' extension array tests,...,NaT,CONTRIBUTOR,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,Should we also be adding `'backfill'`?\r\n\r\n...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52113,1635005677,PR_kwDOAA0YD85MmmeZ,52113,PERF: Use String HashTable in value_counts,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] xref #14860 (Replace xxxx with the GitHu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52112,1634970968,PR_kwDOAA0YD85MmfK6,52112,BUG: Fix getsizeof when using Series(obj) and ...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,Calling __sizeof__ to compute the size of an o...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52111,1634813418,PR_kwDOAA0YD85Ml96Y,52111,PERF: DatetimeIndex comparison with Timestamp ...,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #52080 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52110,1634795770,I_kwDOAA0YD85hcQD6,52110,"DEPR: NDFrame.to_period, to_timestamp, tz_loca...",...,NaT,MEMBER,NaN,NaN,NaN,These are methods that operate on the index/co...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52108,1634668805,I_kwDOAA0YD85hbxEF,52108,BUG: suppressed character limit save file,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52106,1634499531,I_kwDOAA0YD85hbHvL,52106,DOC: MonthBegin suggestion to get start of cur...,...,NaT,MEMBER,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52105,1634430552,I_kwDOAA0YD85ha25Y,52105,BUG: Is offsets.YearBegin working as expected?,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52104,1634178365,PR_kwDOAA0YD85Mj2TP,52104,PERF: use non-copying path for Groupby.skew,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,It wouldn't surprise me if there are contiguit...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52103,1633946764,PR_kwDOAA0YD85MjENn,52103,ENH: bfill for interval indexing added GH#5150...,...,NaT,NONE,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #51503\r\n- [x] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52102,1633924715,I_kwDOAA0YD85hY7Zr,52102,ENH: Enable using a boolean `loc` in a non-boo...,...,NaT,CONTRIBUTOR,NaN,NaN,NaN,### Feature Type\n\n- [ ] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52099,1633529148,I_kwDOAA0YD85hXa08,52099,BUG: Quantile function only works when Catego...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52098,1633085792,I_kwDOAA0YD85hVulg,52098,BUG: `bar_label()` on Series bar plot (`.plot(...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52097,1633053430,PR_kwDOAA0YD85MgCwQ,52097,DOC: improve (dark) theme getting started tuto...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [x] closes #51860 \r\n- [ ] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52094,1632918311,I_kwDOAA0YD85hVFsn,52094,BUG: inconsistent returned types for `pd.to_da...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52093,1632814814,I_kwDOAA0YD85hUsbe,52093,BUG: AttributeError raised with pd.concat betw...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52091,1632637435,I_kwDOAA0YD85hUBH7,52091,BUG or as expected/designed?: Generating times...,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52087,1632260292,PR_kwDOAA0YD85MdXiC,52087,BUG: Fix some more arrow CSV tests,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52086,1632176652,I_kwDOAA0YD85hSQoM,52086,BUG:,...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/52085,1632120349,I_kwDOAA0YD85hSC4d,52085,BUG: Cumprod failing with type float[pyarrow],...,NaT,NONE,NaN,NaN,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52083,1632003201,PR_kwDOAA0YD85McgR6,52083,PERF: improve 2D array access / transpose() fo...,...,NaT,MEMBER,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...,xref https://github.com/pandas-dev/pandas/issu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52082,1631255579,PR_kwDOAA0YD85MZ-hi,52082,DataFrame pivot_table nunique aggfunc test GH#...,...,NaT,CONTRIBUTOR,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #29080 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/52081,1631173495,PR_kwDOAA0YD85MZtGj,52081,DEPR: be stricter in assert_almost_equal,...,NaT,MEMBER,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN

In [69]:
js = pd.read_json('https://api.github.com/repos/pandas-dev/pandas/issues')

In [71]:
js.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'draft', 'pull_request', 'body', 'reactions',
       'timeline_url', 'performed_via_github_app', 'state_reason'],
      dtype='object')

In [73]:
js['user'][0]

{'login': 'whooolemilk',
 'id': 74092547,
 'node_id': 'MDQ6VXNlcjc0MDkyNTQ3',
 'avatar_url': 'https://avatars.githubusercontent.com/u/74092547?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/whooolemilk',
 'html_url': 'https://github.com/whooolemilk',
 'followers_url': 'https://api.github.com/users/whooolemilk/followers',
 'following_url': 'https://api.github.com/users/whooolemilk/following{/other_user}',
 'gists_url': 'https://api.github.com/users/whooolemilk/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/whooolemilk/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/whooolemilk/subscriptions',
 'organizations_url': 'https://api.github.com/users/whooolemilk/orgs',
 'repos_url': 'https://api.github.com/users/whooolemilk/repos',
 'events_url': 'https://api.github.com/users/whooolemilk/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/whooolemilk/received_events',
 'type': 'User',
 'site_admin': False}

In [74]:
df = pd.read_excel('/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas/data set/drive-download-20221212T113845Z-001/Attribute DataSet.xlsx')

In [75]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [76]:
df.to_json('test.json')

In [77]:
pwd

'/Users/madhu'

In [78]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [83]:
# store the data in form of data frame inside your system
df.to_csv("/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas//test.csv")

In [84]:
# store the data with your own custome seperator
df.to_csv("/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas//test1.csv",sep = '#')

In [85]:
# remove the indexes from test.csv
df.to_csv("/Users/madhu/Desktop/Data Science/iNeuron/Python/Everyday class/pandas//test2.csv",index = False)

Mysql : 
    
    1. Create a  table attribute dataset and dress dataset
    2. Do a bulk load for these two table for respective dataset 
    3. read these dataset in pandas as a dataframe 
    4. Convert attribute dataset in json format 
    5. Store this dataset into mongodb
    6. in sql task try to perform left join operation with attrubute dataset and dress dataset on column Dress_ID
    7. Write a sql query to find out how many unique dress that we have based on dress id 
    8. Try to find out how mnay dress is having recommendation 0
    9. Try to find out total dress sell for individual dress id 
    10. Try to find out a third highest most selling dress id 
    
    
    sudhanshu@ineuron.ai